### ISSUE TITLE
 getCredentialChainCreds always returns undefined

### ISSUE THREAD

**Issue by JoshRagem** [aws/aws-sigv4-auth-cassandra-nodejs-driver-plugin#4]
https://github.com/aws/aws-sigv4-auth-cassandra-nodejs-driver-plugin/blob/220aaaea157d7845cf94c1a604a162ca07346e05/lib/sigv4-auth-provider.js#L74-L83 this function will always return undefined because `chain.resolve(...)` is async and the callback will not run until after getCredentialChainCreds returns

**Comment by bhouse99** [comment]
With the recent PR I believe the issue is resolved.
